apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views
app_name = 'home'
urlpatterns = [

    path('', views.index, name='home'),
    path('floors/', views.floors_list, name='floors_list'),
    path('departments/', views.departments_list, name='departments_list'),
    path('positions/', views.positions_list, name='positions_list'),
    path('custodiams/', views.custodiams_list, name='custodiams_list'),
    
    #para inventario
    path('brands/', views.brands_list, name='brands_list'),
    path('prototypes/', views.prototypes_list, name='prototypes_list'),
    path('products/', views.products_list, name='products_list'),
    path('productAssignments/', views.productAssignments_list, name='productAssignments_list'),


    #para recursos
    path('hardwares/', views.hardwares_list, name='hardwares_list'),
    path('softwares/', views.softwares_list, name='softwares_list'),
    path('displayNames/', views.displayNames_list, name='displayNames_list'),
    path('dateOperations/', views.dateOperations_list, name='dateOperations_list'),
    path('ipAssignations/', views.ipAssignations_list, name='ipAssignations_list'),
    # Coloca la expresión regular al final para evitar conflictos
    re_path(r'^.*\.*', views.pages, name='pages'),

]

config/urls.py
from django.contrib import admin
from django.urls import include,path  # add this

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hierarchy/', include('hierarchy.urls')),  # Incluye las URLs de 'hierarchy'
    path('inventory/', include('inventory.urls')),  # Incluye las URLs de 'inventory'
    path('resources/', include('resources.urls')),  # Incluye las URLs de 'resources'
    path("", include("apps.authentication.urls")),  # Rutas de autenticación
    path('', include("apps.home.urls")),  # Rutas de home
    path('select2/', include('django_select2.urls')),
]

apps/templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                <a target="_blank" 
                   href="https://appseed.us/admin-dashboards/django" 
                   class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
               &copy; <a target="_blank" 
                         href="https://bit.ly/3fKQZaL">Creative-Tim</a> 
               - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </div>
    </footer>

apps/templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a href="https://appseed.us/admin-dashboards/django" 
                 class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="https://bit.ly/3fKQZaL" 
                 class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a> 
                 - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </footer>

apps/templates/includes/navigation-fullscreen.html
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="/static/assets/img/brand/white.png" alt="Argon Design - Template Starter Logo.">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="/static/assets/img/brand/blue.png">
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="{% url 'login' %}" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'register' %}" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
        </li>
      </ul>
      <hr class="d-lg-none" />
    
    </div>
  </div>
</nav>

apps/templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
      <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
        <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input class="form-control" placeholder="Search" type="text">
          </div>
        </div>
        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </form>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
            <!-- Dropdown header -->
            <div class="px-3 py-3">
              <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">13</strong> notifications.</h6>
            </div>
            <!-- List group -->
            <div class="list-group list-group-flush">
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-1.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-2.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>3 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-3.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>5 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Your posts have been liked a lot.</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-5.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>3 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
                  </div>
                </div>
              </a>
            </div>
            <!-- View all -->
            <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-ungroup"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">
            <div class="row shortcuts px-4">
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                  <i class="ni ni-calendar-grid-58"></i>
                </span>
                <small>Calendar</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                  <i class="ni ni-email-83"></i>
                </span>
                <small>Email</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                  <i class="ni ni-credit-card"></i>
                </span>
                <small>Payments</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-green">
                  <i class="ni ni-books"></i>
                </span>
                <small>Reports</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
                  <i class="ni ni-pin-3"></i>
                </span>
                <small>Maps</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-yellow">
                  <i class="ni ni-basket"></i>
                </span>
                <small>Shop</small>
              </a>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="/profile.html" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a target="_blank" href="http://appseed.us/support" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

apps/templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

apps/templates/includes/sidenav.html
<nav class="sidenav navbar navbar-vertical fixed-left navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header align-items-center">
      <a class="navbar-brand" href="/">
        <img src="/static/assets/img/brand/blue.png" class="navbar-brand-img" alt="Argon Design - Jinja Template Logo.">
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <!-- Dashboard -->
          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="/">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Dashboard</span>
            </a>
          </li>

          <!-- Bloque 1: Estructura Organizacional -->
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#organizacional" aria-expanded="true">
              <i class="ni ni-briefcase-24 text-info"></i>
              <span class="nav-link-text">Estructura Organizacional</span>
            </a>
            <div class="collapse show" id="organizacional" data-parent="#sidenav-collapse-main">
              <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:floors_list' %}">
                    <i class="ni ni-building text-orange"></i>
                    <span class="nav-link-text">Piso</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:departments_list' %}">
                    <i class="ni ni-world-2 text-primary"></i>
                    <span class="nav-link-text">Departamento</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:positions_list' %}">
                    <i class="ni ni-paper-diploma text-primary"></i>
                    <span class="nav-link-text">Cargo</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:custodiams_list' %}">
                    <i class="ni ni-badge text-primary"></i>
                    <span class="nav-link-text">Custodio</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>

          <!-- Bloque 2: Gestión de Productos -->
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#gestion-productos" aria-expanded="true">
              <i class="ni ni-box-2 text-success"></i>
              <span class="nav-link-text">Gestión de Productos</span>
            </a>
            <div class="collapse show" id="gestion-productos" data-parent="#sidenav-collapse-main">
              <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:productAssignments_list' %}">
                    <i class="ni ni-archive-2 text-orange"></i>
                    <span class="nav-link-text">Asignación de Producto</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:brands_list' %}">
                    <i class="ni ni-tag text-primary"></i>
                    <span class="nav-link-text">Marca</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:prototypes_list' %}">
                    <i class="ni ni-tv-2 text-primary"></i>
                    <span class="nav-link-text">Modelos de Producto</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:products_list' %}">
                    <i class="ni ni-bag-17 text-primary"></i>
                    <span class="nav-link-text">Producto</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>

          <!-- Bloque 3: Recursos Tecnológicos -->
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#recursos-tecnologicos" aria-expanded="true">
              <i class="ni ni-laptop text-warning"></i>
              <span class="nav-link-text">Recursos Tecnológicos</span>
            </a>
            <div class="collapse show" id="recursos-tecnologicos" data-parent="#sidenav-collapse-main">
              <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:hardwares_list' %}">
                    <i class="ni ni-tablet-button text-orange"></i>
                    <span class="nav-link-text">Hardware</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:softwares_list' %}">
                    <i class="ni ni-chart-bar-32 text-primary"></i>
                    <span class="nav-link-text">Software</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:displayNames_list' %}">
                    <i class="ni ni-laptop text-primary"></i>
                    <span class="nav-link-text">Display Name</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:dateOperations_list' %}">
                    <i class="ni ni-calendar-grid-58 text-primary"></i>
                    <span class="nav-link-text">Fecha de Operación</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>

          <!-- Bloque 4: Redes y Direcciones IP -->
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#redes-ip" aria-expanded="true">
              <i class="ni ni-world text-danger"></i>
              <span class="nav-link-text">Redes y Direcciones IP</span>
            </a>
            <div class="collapse show" id="redes-ip" data-parent="#sidenav-collapse-main">
              <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'home:ipAssignations_list' %}">
                    <i class="ni ni-pin-3 text-primary"></i>
                    <span class="nav-link-text">Asignación de IP</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>

          <!-- Profile -->
          <li class="nav-item">
            <a class="nav-link {% if 'profile' in segment %} active {% endif %}" href="/profile.html">
              <i class="ni ni-single-02 text-yellow"></i>
              <span class="nav-link-text">Profile</span>
            </a>
          </li>

          <!-- Tables -->
          <li class="nav-item">
            <a class="nav-link {% if 'tables' in segment %} active {% endif %}" href="/tables.html">
              <i class="ni ni-bullet-list-67 text-default"></i>
              <span class="nav-link-text">Tables</span>
            </a>
          </li>
        </ul>

        <!-- Divider -->
        <hr class="my-3">

        <!-- Resources Section -->
        <h6 class="navbar-heading p-0 text-muted">
          <span class="docs-normal">Resources</span>
        </h6>
        <ul class="navbar-nav mb-md-3">
          <li class="nav-item">
            <a class="nav-link" target="_blank" href="#">
              <i class="ni ni-archive-2"></i>
              <span class="nav-link-text">Prueba</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>